name: 'Sanitize branch name'
author: 'Cole Bittel'
description: 'Sanitize branch name for DNS creation'
inputs:
  GITHUB_DISPATCH_WORKFLOW_TOKEN:
    description: 'GitHub token (PAC) with permissions to trigger a workflow_dispatch event on the repo'
    required: true
  WORKFLOW_DISPATCH_FILE_NAME:
    description: 'GitHub workflow file name (including `.yaml`) for the workflow to dispatch (eg. `deploy_primary_dispatch.yaml`)'
    required: true
  ENV:
    description: 'Kubernetes cluster to deploy to'
    required: true
  WORKFLOW_FILE_REF:
    description: 'The GitHub branch to source the WORKFLOW_DISPATCH_FILE_NAME from'
    required: false
    default: 'refs/heads/main'
  ALLOW_CHAINED_DEPLOYMENTS:
    description: 'Allow workflows to chain together. Eg. if you are deploying to staging, should it be allowed to trigger a production deployment on success?'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_DISPATCH_WORKFLOW_TOKEN }}
    - ${{ inputs.WORKFLOW_DISPATCH_FILE_NAME }}
    - ${{ inputs.ENV }}
    - ${{ inputs.WORKFLOW_FILE_REF }}
    - ${{ inputs.ALLOW_CHAINED_DEPLOYMENTS }}
