name: "Deploy Github Actions workflows"
description: "Deploy a common Github Action workflow to a repo."
author: "bittelc"
inputs:
  GITHUB_TOKEN:
    description: "Github secret token to allow automated publishing of artifacts to a release."
  GHA_DEPLOYMENT_FOLDER:
    description: "Folder name where the to-be-deployed Github Actions reside."
  COMMIT_MESSAGE:
    description: "Custom message for commit. Default message: Updating Github Action workflows."
  GHA_DEPLOY_BRANCH_NAME:
    description: "Name of the branch to be created. Default branch name: update_gha_source."
runs:
  using: "docker"
  image: "Dockerfile"