# action.yml
name: 'dbt-action'
description: 'dbt (data build tool) github action'
inputs:
    dbt-command:
        description: 'Command to execute'
        required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dbt-command }}